plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zhinian.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.zhinian.app"
        minSdk 26          // Android 8.0+(2017)
        targetSdk 35
        versionCode 3
        versionName "1.0.2"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.11.0'
}
